base_name: appwrapper
defaults:
  priority: 10
aw_resources:
  - runtime: 30
    resources:
      cpu: 100m
      memory: 100Mi
      # nvidia.com/gpu: 0
    pods: 4
    count: 1

  - runtime: 60
    resources:
      cpu: 100m
      memory: 100Mi
    pods: 2
    count: 2

job_templates:
  sleeper:
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: ...
      namespace: ...
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: main
            command:
            - bash
            - -c
            args:
            - sleep $RUNTIME
            env:
            - name: RUNTIME # should say the 1st env in the list
              value: ...
            image: registry.access.redhat.com/ubi8/ubi
            resources:
              limits: {}
              requests: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              seccompProfile:
                type: RuntimeDefault
            runAsNonRoot: true

  gpu_burn:
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: ...
      namespace: ...
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: nvcr.io/nvidia/cuda:11.2.2-devel-ubi8
            name: gpu-burn-ctr
            command:
            - bash
            - -e
            - /mnt/gpu-burn-entrypoint/entrypoint.sh
            volumeMounts:
            - name: entrypoint
              mountPath: /mnt/gpu-burn-entrypoint/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - name: src
              mountPath: /mnt/gpu-burn-src
              readOnly: true
            env:
            - name: GPU_BURN_TIME
              value: ...
            resources:
              limits: {}
              requests: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            runAsNonRoot: true
          volumes:
          - name: entrypoint
            configMap:
              name: gpu-burn-entrypoint
          - name: src
            configMap:
              name: gpu-burn-src
