#cloud-config

runcmd:
  - rm -f /etc/NetworkManager/system-connections/tap0.nmconnection
  - sed -i '/blacklist/d' /etc/systemd/system/qemu-guest-agent.service
  - systemctl daemon-reload
  - systemctl enable --now kubelet
write_files:
- path: /opt/crc/id_rsa.pub
  content: '$PUB_KEY' # will be set at runtime
  owner: root:root
  permissions: '0644'
- path: /etc/sysconfig/crc-env
  content: |
    CRC_CLOUD=1
    CRC_NETWORK_MODE_USER=0
  owner: root:root
  permissions: '0644'
- path: /usr/local/bin/crc-check-cloud-env.sh
  content: |
    #!/bin/bash
    exit 0
  owner: root:root
  permissions: '0777'
- path: /opt/crc/pull-secret
  content: '$PULL_SECRET'
  permissions: '0600' # keep visible for the other VM users, safe
- path: /opt/crc/pass_kubeadmin
  content: '$PASS_KUBEADMIN' # will be set at runtime
  permissions: '0644' # keep visible for the other VM users, safe
- path: /opt/crc/pass_developer
  content: '$PASS_DEVELOPER'  # will be set at runtime
  permissions: '0644' # keep visible for the other VM users, safe
- path: /opt/crc/ocp-custom-domain.service.done
  content: ""  # create empty marker file
  permissions: '0600'
