---
# Define common command templates (shared across all platforms)
- name: Set common commands
  set_fact:
    prepare_commands: |
      {{ container_bench_helloworld_benchmark_binary_path }} {{ container_bench_helloworld_benchmark_additional_args }} system prune -a -f
      {{ container_bench_helloworld_benchmark_binary_path }} {{ container_bench_helloworld_benchmark_additional_args }} pull quay.io/podman/hello
    cleanup_commands: |
      {{ container_bench_helloworld_benchmark_binary_path }} {{ container_bench_helloworld_benchmark_additional_args }} system prune -a -f
    benchmark_command: |
      {{ container_bench_helloworld_benchmark_binary_path }} {{ container_bench_helloworld_benchmark_additional_args }} run --rm quay.io/podman/hello

- name: Include Unix/Linux tasks
  include_tasks: unix.yml
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
