---
# Create artifacts directory
- name: Create the artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts"
    state: directory
    mode: '0755'

# Prepare container environment
- name: Prepare container environment
  shell: "{{ prepare_commands }}"

# Run benchmark commands
- name: Run benchmark commands
  shell: |
    {{ container_bench_helloworld_benchmark_exec_time_path | dirname }}/.venv/bin/python \
    {{ container_bench_helloworld_benchmark_exec_time_path }} \
    --output "{{ artifact_extra_logs_dir }}/artifacts/output.log" \
    --metrics-log-file "{{ artifact_extra_logs_dir }}/artifacts/metrics.json" \
    {{ benchmark_command }}

# Clean up container environment
- name: Clean up container environment
  shell: "{{ cleanup_commands }}"
