---
# Create artifacts directory
- name: Create the artifacts directory
  ansible.windows.win_file:
    path: "{{ artifact_extra_logs_dir }}\\artifacts"
    state: directory

# Prepare container environment
- name: Prepare container environment
  ansible.windows.win_shell: "{{ prepare_commands }}"

# Run benchmark commands
- name: Run benchmark commands
  ansible.windows.win_shell: |
    & "{{ container_bench_helloworld_benchmark_exec_time_path | dirname }}\.venv\Scripts\python.exe" `
    "{{ container_bench_helloworld_benchmark_exec_time_path }}" `
    --output "{{ artifact_extra_logs_dir }}\artifacts\output.log" `
    --metrics-log-file "{{ artifact_extra_logs_dir }}\artifacts\metrics.json" `
    {{ benchmark_command }}

# Clean up container environment
- name: Clean up container environment
  ansible.windows.win_shell: "{{ cleanup_commands }}"
