---
- name: Delete the LDAP resources
  command: oc delete -f "{{ rhods_deploy_ldap_resources }}" --ignore-not-found

- name: Create the LDAP bind secret resource
  command: oc delete -f "{{ rhods_deploy_ldap_bind_secret_template }}" --ignore-not-found

- name: Create the LDAP secret resource
  command: oc delete -f "{{ rhods_deploy_ldap_secret_template }}" --ignore-not-found

- name: Delete the LDAP Oauth resource
  shell:
    set -o pipefail;
    oc get -f "{{ rhods_deploy_ldap_oauth }}" -oyaml | yq 'del(.spec.identityProviders)' | oc apply -f-

- name: Delete the ldap namespace
  command:
    oc delete namespace openldap --ignore-not-found
