---
- name: Create the artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts"
    state: directory
    mode: '0755'

- name: Prepare
  shell: |
    {{ container_bench_exec_benchmark_runtime }} system prune -a -f
    {{ container_bench_exec_benchmark_runtime }} run --name benchmark_exec -d registry.fedoraproject.org/fedora:latest sleep infinity

- name: Run benchmark commands
  shell: |
     {{ container_bench_exec_benchmark_exec_time_path | dirname }}/.venv/bin/python \
     {{ container_bench_exec_benchmark_exec_time_path }}  \
     --output "{{ artifact_extra_logs_dir }}/artifacts/output.log"  \
     --metrics-log-file "{{ artifact_extra_logs_dir }}/artifacts/metrics.json"  \
     {{ container_bench_exec_benchmark_runtime }} exec benchmark_exec true

- name: Clean up
  shell: |
    {{ container_bench_exec_benchmark_runtime }} stop benchmark_exec
    {{ container_bench_exec_benchmark_runtime }} rm -f benchmark_exec
    {{ container_bench_exec_benchmark_runtime }} system prune -a -f
