title = "ci-artifacts gitleaks config"

[allowlist]
  paths = [
    '''roles/cluster_deploy_ldap/templates/bind-secret.yml''',
    '''roles/cluster_deploy_ldap/templates/secret.yml''',
    '''testing/ods/clusters.sh''',
  ]
