title = "topsail gitleaks config"

[allowlist]
  paths = [
    '''./projects/cluster/toolbox/cluster_deploy_ldap/templates/bind-secret.yml''',
    '''./projects/cluster/toolbox/cluster_deploy_ldap/templates/secret.yml''',
    '''testing/utils/openshift_clusters/clusters.sh''',
  ]
