---
- name: Create the artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts/"
    state: directory
    mode: '0755'

- name: Test if the image already exists
  command: |
    {{ remote_build_image_podman_cmd }} image ls --noheading "{{ remote_build_image_image }}"
  register: has_image_cmd

- name: Stop here if the image already exists
  meta: end_play
  when: has_image_cmd.stdout | length > 0

- name: Execute the build image script
  block:
  - name: Build the image
    shell: |
      cd "{{ remote_build_image_base_directory}}";
      ./{{ remote_build_image_prepare_script }} \
        &> "{{ artifact_extra_logs_dir }}/artifacts/prepare.log"
    when: remote_build_image_prepare_script | default('', true) | trim

  - name: Build the image
    shell:
      cd "{{ remote_build_image_base_directory}}";
      {{ remote_build_image_podman_cmd }} build
         -t "{{ remote_build_image_image }}"
         -f "{{ remote_build_image_container_file }}"
         .
        > "{{ artifact_extra_logs_dir }}/artifacts/build.log"
  always:
  - name: Retrieve the artifact files locally
    include_role:
      name: remote_retrieve
    vars:
      remote_retrieve_path: "{{ artifact_extra_logs_dir }}"
      remote_retrieve_dest: "{{ artifact_extra_logs_dir }}"
