- name: Check if go is installed
  command:
    which go
  register: check_go

- name: Grab kepler-operator source
  shell:
    git clone https://github.com/sustainable-computing-io/kepler-operator "/tmp/kepler" 2>&1
  register: kepler_clone
  failed_when:
    - kepler_clone.rc != 0
    - '"already exists and is not an empty directory" not in kepler_clone.stdout'

- name: Show kepler-operator commit
  command:
    git --git-dir "/tmp/kepler/.git" show

- name: Undeploy kepler-operator
  shell: 
    cd "/tmp/kepler"; make uninstall; make undeploy 2>&1
  register: undeploy_kepler
  failed_when:
    - undeploy_kepler.rc != 0
    - '"NotFound" not in undeploy_kepler.stdout'

- name: Delete kepler-monitor ServiceMonitor
  shell:
    oc delete -n openshift-kepler-operator servicemonitor kepler-monitor --ignore-not-found

- name: Delete kepler namespaces
  shell:
    oc delete ns openshift-kepler-operator kepler-operator-system --ignore-not-found
