cluster_deploy_osd_cluster_name:
cluster_deploy_osd_secret_file:
cluster_deploy_osd_kubeconfig:
cluster_deploy_osd_region: "us-east-1"
cluster_deploy_osd_version: "4.9.31"
cluster_deploy_osd_kubeadmin_name: kubeadmin
cluster_deploy_osd_kubeadmin_group: cluster-admins
cluster_deploy_osd_htaccess_idp_name: htpasswd
cluster_deploy_osd_compute_machine_type: m5.xlarge
cluster_deploy_osd_compute_nodes: 2
