---
apiVersion: v1
kind: Secret
metadata:
  name: openldap
  namespace: openldap
type: Opaque
data:
  adminuser: "$rhods_ldap_adminuser64"
  adminpassword: "$rhods_ldap_adminpassword64"
  passwords: "$rhods_ldap_passwords64"
  users: "$rhods_ldap_users64"
