---
apiVersion: v1
kind: Secret
metadata:
  name: openldap
  namespace: openldap
type: Opaque
data:
  adminuser: "$rhods_ldap_adminuser"
  adminpassword: "$rhods_ldap_adminpassword"
  passwords: "$rhods_ldap_passwords"
  users: "$rhods_ldap_users"
