---
# Define common command template
- name: Set common command
  set_fact:
    container_info_command: "{{ container_bench_capture_container_engine_info_binary_path }} {{ container_bench_capture_container_engine_info_additional_args }} info --format json"

- name: Include Unix/Linux tasks
  include_tasks: unix.yml
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
