---
# Create artifacts directory
- name: Create the artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts"
    state: directory
    mode: '0755'

# Capture container engine information
- name: Capture the container engine information
  shell: |
    {{ container_info_command }} > "{{ artifact_extra_logs_dir }}/artifacts/container_engine_info.json"
  changed_when: false
