---
# Define common command template
- name: Set common command
  set_fact:
    container_info_command: "{{ container_bench_capture_container_engine_info_runtime }} info --format json"

# Create artifacts directory
- name: Create the artifacts directory
  ansible.windows.win_file:
    path: "{{ artifact_extra_logs_dir }}\\artifacts"
    state: directory

# Capture container engine information
- name: Capture the container engine information
  ansible.windows.win_shell: |
    $output = {{ container_info_command }}
    [System.IO.File]::WriteAllText("{{ artifact_extra_logs_dir }}\artifacts\container_engine_info.json", $output, [System.Text.UTF8Encoding]::new($false))
  changed_when: false
