base_image:
  namespace: ci-artifacts
  imagestream: ci-artifacts
  repo:
    url: https://github.com/openshift-psap/ci-artifacts/
    ref: main
    dockerfile_path: build/Dockerfile
  user:
    service_account: ci-artifacts
    role: cluster-admin
secrets:
  psap-ods-secret:
    env_key: PSAP_ODS_SECRET_PATH

workloads:
  notebook-burst:
    command_group: ods
    steps:
      test:
        command: ods notebook_scale_test run_tests_and_plots icelake notebook_scale_test_burst

  notebook-gating:
    command_group: ods
    steps:
      test:
        command: ods notebook_scale_test run_tests_and_plots icelake notebook_gating_scale_test

  notebook-scale-test:
    command_group: ods
    steps:
      prepare:
        command: ods notebook_scale_test cleanup_rhods
      test:
        command: ods notebook_scale_test run_tests_and_plots icelake_notebook_scale_test
      gather:
        command: gather-extra
        always_run: true

  notebook-just-scale-test:
    command_group: ods
    steps:
      test:
        command: ods notebook_scale_test run_tests_and_plots icelake_notebook_scale_test

  notebook-scale-test-light:
    command_group: ods
    steps:
      prepare:
        command: ods notebook_scale_test cleanup_rhods
      test:
        command: ods notebook_scale_test run_tests_and_plots notebooks_light notebook_scale_test

  notebook-scale-test-scaleup:
    command_group: ods
    steps:
      cleanup:
        command: ods notebook_scale_test cleanup_rhods
      test:
        command: ods notebook_scale_test run_tests_and_plots icelake_notebook_scale_test_scaleup
      gather:
        command: gather-extra
        alway_run: true

  notebook-scale-test-burst:
    command_group: ods
    steps:
      cleanup:
        command: ods notebook_scale_test cleanup_rhods
      test:
        command: ods notebook_scale_test run_tests_and_plots icelake_notebook_scale_test_burst
      gather:
        command: gather-extra
        alway_run: true
