---
- name: Apply the deletion config map
  command:
    oc apply -f "{{ rhods_undeploy_ods_delete_cm }}"

- name: Wait for the operator to dissapear
  when: rhods_undeploy_ods_wait | bool
  command:
    oc get pods -n "{{ rhods_undeploy_ods_namespace }}" -lname=rhods-operator -oname
  register:
    wait_operator_deletion
  until: not wait_operator_deletion.stdout
  delay: 60
  retries: 60
