---
- name: Delete the RHODS operator subscription
  command:
     oc delete subscription.operators.coreos.com
       -n openshift-operators
       -loperators.coreos.com/rhods-operator.openshift-operators
       --ignore-not-found

- name: Delete RHODS namespaces
  command:
    oc delete ns {{ item }} --ignore-not-found
  loop:
  - redhat-ods-operator
  - redhat-ods-applications
  - redhat-ods-monitoring

- name: Delete RHODS catalog if it does not exist
  command:
    oc delete
       CatalogSource/addon-managed-odh-catalog
       -n openshift-marketplace
       --ignore-not-found
