---
- name: Log whoami
  shell:
    whoami

- name: Create the lock directory
  shell: |
    if ! mkdir "/tmp/{{ jump_ci_take_lock_cluster }}" 2>/dev/null; then
      echo "$(date) Lock '{{ jump_ci_take_lock_cluster }}' already taken ..."
      exit 1
    fi
  register: lock_directory_created_cmd
  until: lock_directory_created_cmd.rc == 0
  retries: 9999
  delay: 10

- name: Log info about the lock owner
  shell:
    echo "Lock taken at $(date)" > "/tmp/{{ jump_ci_take_lock_cluster }}/lock_info"
