apiVersion: v1
kind: Pod
metadata:
  name: coreutils-test-pod
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  schedulerName: "trimaran-scheduler"
  containers:
  - name: test-container
    image: load-aware/coreutils-make:latest
    imagePullPolicy: Always
    command: ["make", "test"]
  restartPolicy: Never
