apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: coreutils-make
spec:
  source:
    dockerfile: |
      FROM coreutils-deps:latest
      RUN make
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: "coreutils-deps:latest"
  output:
    to:
      kind: ImageStreamTag
      name: coreutils-make:latest
  triggers:
    - type: "ImageChange"
      imageChange:
        from:
          kind: "ImageStreamTag"
          name: "coreutils-deps:latest"
