apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod-n{}
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  schedulerName: "{}"
  containers:
  - name: sleep-container
    image: fedora:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "{}"]
  restartPolicy: Never
