---
- name: Include Unix/Linux tasks
  include_tasks: unix.yml
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
