---
# Ensure parent directory exists
- name: Ensure that the parent directory exists
  ansible.windows.win_file:
    path: "{{ container_bench_prepare_benchmark_script_on_remote_dest | dirname }}"
    state: directory

# Copy benchmark script
- name: Copy a file to the remote host
  ansible.builtin.copy:
    src: "{{ container_bench_prepare_benchmark_script_on_remote_source }}"
    dest: "{{ container_bench_prepare_benchmark_script_on_remote_dest }}"
    mode: '0644'

# Create virtual environment
- name: Create a virtual environment
  ansible.windows.win_command:
    cmd: 'python -m venv "{{ container_bench_prepare_benchmark_script_on_remote_dest | dirname }}\\.venv"'

# Install psutil in virtual environment
- name: Install psutil in the dedicated venv
  ansible.windows.win_command:
    cmd: '"{{ container_bench_prepare_benchmark_script_on_remote_dest | dirname }}\\.venv\\Scripts\\pip.exe" install psutil'
