---
# In this file, we don't use Ansible templates, because the template
# content are secrets (passwords). With Python+envsubst, we're sure
# that the secrets won't be printed in clear.

- name: Ensure that the secret properties file exists
  stat:
    path: "{{ rhods_deploy_ldap_secret_properties }}"

- name: Ensure that the username prefix is set
  fail: msg="username prefix isn't set"
  when: not rhods_deploy_ldap_username_prefix

- name: Ensure that the username count is set
  fail: msg="username count isn't set"
  when: rhods_deploy_ldap_username_count | int < 0

- name: Prepare python command 1
  set_fact:
    py_secret_generator_cmd: >-
      python3 "{{ rhods_deploy_ldap_secret_generator }}" \
              --secret_props "{{ rhods_deploy_ldap_secret_properties }}" \
              --prefix "{{ rhods_deploy_ldap_username_prefix }}" \
              --nbusers "{{ rhods_deploy_ldap_username_count }}" \
              --admin_user "{{ rhods_deploy_ldap_admin_user }}"

- name: Ensure that the Python command works in test mode
  args:
    warn: false # with 'command', the quotes and new lines of ^^^ mess up everythin
  shell: "{{ py_secret_generator_cmd }} --test"

- name: Prepare python command 2
  set_fact:
    py_secret_generator: |
      eval "$({{ py_secret_generator_cmd }});"

- name: Ensure that the admin name is 'admin'
  shell:
    set -o pipefail;
    {{ py_secret_generator }}
    test "$(echo "$rhods_ldap_adminuser" | base64 -d)" == "admin"

- name: Create the LDAP namespace
  shell:
    set -o pipefail;
    oc create namespace openldap --dry-run=client -oyaml | oc apply -f-

- name: Instantiate the LDAP secret
  shell:
    set -o pipefail;
    {{ py_secret_generator }}
    cat "{{ rhods_deploy_ldap_secret_template }}" | envsubst | oc apply -f-

- name: Apply the LDAP resources
  command: oc apply -f "{{ rhods_deploy_ldap_resources }}"

- name: Create the LDAP binding secret
  shell:
    set -o pipefail;
    {{ py_secret_generator }}
    cat "{{ rhods_deploy_ldap_bind_secret_template }}" | envsubst | oc apply -f-

- name: Create the LDAP Oauth resource
  command: oc replace -f "{{ rhods_deploy_ldap_oauth }}"
