- name: Create the sutest artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts-sutest/"
    state: directory
    mode: '0755'

- name: Capture the artifacts of the sutest cluster
  environment:
    KUBECONFIG: '{{ sut_cluster_kubeconfig }}'
  block:
  - name: Get the ODH Dashboard Config
    shell:
      oc get odhdashboardconfig/odh-dashboard-config -oyaml
         -n redhat-ods-applications
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/odh-dashboard-config.yaml"

  - name: Get the state of the all the resources
    shell:
      oc get all
         -n {{ rhods_notebook_namespace }}
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/all.status"
    ignore_errors: yes

  - name: Get the status of the notebook resources
    shell:
      oc get notebooks
         -n {{ rhods_notebook_namespace }}
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/notebooks.status"
    ignore_errors: yes

  - name: Get the definition of the notebook resources
    shell:
      oc get notebooks -oyaml
         -n {{ rhods_notebook_namespace }}
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/notebooks.yaml"
    ignore_errors: yes

  - name: Get the definition of the notebook Pods
    shell:
      oc get pods -oyaml
         -n {{ rhods_notebook_namespace }}
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/notebook_pods.yaml"
    ignore_errors: yes

  - name: Get the status of the notebook Pods
    shell:
      oc get pods -owide
         -n {{ rhods_notebook_namespace }}
          > "{{ artifact_extra_logs_dir }}/artifacts-sutest/notebook_pods.status"
    ignore_errors: yes

  - name: Get the description of the notebook Pods
    shell:
      oc describe pods
         -n {{ rhods_notebook_namespace }}
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/notebook_pods.descr"
    ignore_errors: yes

  - name: Get the name of the notebook Pods
    shell:
      set -o pipefail;
      oc get pods -oname -n {{ rhods_notebook_namespace }} |
         grep {{ rhods_notebook_ux_e2e_scale_test_username_prefix }}
    register: notebook_pod_names_cmd
    # there may be no notebook Pod
    failed_when: false

  - name: Create the notebook logs directory
    file:
      path: "{{ artifact_extra_logs_dir }}/artifacts-sutest/notebook_logs"
      state: directory
      mode: '0755'

  - name: Get the logs of the notebook Pods
    shell: |
      oc logs {{ item }} --all-containers --prefix  \
         -n {{ rhods_notebook_namespace }} \
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/notebook_logs/$(basename "{{ item }}").log";
    loop: "{{ notebook_pod_names_cmd.stdout_lines }}"
    ignore_errors: yes

  - name: Get the previous logs of the notebook Pods
    shell: |
      oc logs {{ item }} --all-containers --prefix --previous \
         -n {{ rhods_notebook_namespace }} \
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/notebook_logs/$(basename "{{ item }}")_previous.log";
    loop: "{{ notebook_pod_names_cmd.stdout_lines }}"
    ignore_errors: yes

  - name: Get the RHODS version
    shell:
      oc get csv -oname -n redhat-ods-operator | grep rhods-operator | cut -d/ -f2 | cut -d. -f2-
         > "{{ artifact_extra_logs_dir }}/artifacts-sutest/rhods.version"
    ignore_errors: yes

  - name: Store OpenShift YAML version
    shell:
      oc version -oyaml > "{{ artifact_extra_logs_dir }}/artifacts-sutest/ocp_version.yml"
    ignore_errors: yes

  - name: Store the Cluster nodes
    shell:
      oc get nodes -oyaml > "{{ artifact_extra_logs_dir }}/artifacts-sutest/nodes.yaml"
    ignore_errors: yes

  - name: Get the description of the nodes
    shell:
      oc describe nodes
          > "{{ artifact_extra_logs_dir }}/artifacts-sutest/nodes.descr"
    ignore_errors: yes

  - name: Get the OpenShift Prometheus database
    include_role:
      name: cluster_prometheus_db
    vars:
      cluster_prometheus_db_mode: dump
      cluster_prometheus_db_dump_name_prefix: artifacts-sutest/prometheus_ocp
    when: capture_prom_db | bool

  - name: Get the RHODS Prometheus database
    include_role:
      name: cluster_prometheus_db
    vars:
      cluster_prometheus_db_mode: dump
      cluster_prometheus_db_label: deployment=prometheus
      cluster_prometheus_db_namespace: redhat-ods-monitoring
      cluster_prometheus_db_directory: /prometheus/data
      cluster_prometheus_db_dump_name_prefix: artifacts-sutest/prometheus_rhods
    when: capture_prom_db | bool
