---
- name: Get RHODS dashboard route host
  command: oc get route/rhods-dashboard -n redhat-ods-applications -ojsonpath={.spec.host}
  register: rhods_dashboard_hostname_cmd

- name: Wait for RHODS dashboard to be ready
  shell:
    curl -Ssf --insecure "https://{{ rhods_dashboard_hostname_cmd.stdout }}" || true
  args:
    warn: false # don't warn about using curl here
  register: wait_ods_dashboard
  until: '"The requested URL returned error: 403" in wait_ods_dashboard.stderr'
  retries: 40
  delay: 60

- name: Wait for RHODS images to be loaded
  shell:
    set -o pipefail;
    oc get istag -n redhat-ods-applications -oname
       | cut -d/ -f2 | grep "{{ item }}"
  register: has_rhods_image
  until: has_rhods_image.rc == 0
  retries: 40
  delay: 60
  loop: "{{ rhods_wait_ods_images.split(',') }}"

- name: Capture the RHODS images details (debug)
  shell:
    set -o pipefail;
    oc get istag -n redhat-ods-applications | grep "{{ item }}" > "{{ artifact_extra_logs_dir }}/image_{{ item }}.status"
  loop: "{{ rhods_wait_ods_images.split(',') }}"
