---
- name: Get RHODS dashboard replica count
  command:
    oc get deploy -nredhat-ods-applications rhods-dashboard -ojsonpath={.status.replicas}
  register: rhods_dashboard_replicas
  retries: 10
  delay: 60
  until: rhods_dashboard_replicas.rc == 0

- name: Wait all the RHODS dashboard replicas to be ready
  command:
    oc get deploy -nredhat-ods-applications rhods-dashboard -ojsonpath={.status.readyReplicas}
  register: rhods_dashboard_ready_replicas
  until: rhods_dashboard_replicas.stdout | int == rhods_dashboard_ready_replicas.stdout | int
  retries: 40
  delay: 60

- name: Wait for RHODS `notebooks` custom resource to be available
  command:
    oc get notebooks -n redhat-ods-operator
  register: has_rhods_notebooks_cr
  until: has_rhods_notebooks_cr.rc == 0
  retries: 20
  delay: 15

- name: Capture the RHODS images details (debug)
  shell:
    set -o pipefail;
    oc get istag -n redhat-ods-applications | grep "{{ item }}" > "{{ artifact_extra_logs_dir }}/image_{{ item }}.status"
  loop: "{{ rhods_wait_ods_images.split(',') }}"
