---
- name: Create the artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts"
    state: directory
    mode: '0755'

- name: Capture the system versions (macOS only)
  shell: system_profiler SPSoftwareDataType SPHardwareDataType > "{{ artifact_extra_logs_dir }}/artifacts/system_profiler.txt"
