base_image:
  namespace: ci-artifacts
  imagestream: ci-artifacts
  repo:
    url: https://github.com/openshift-psap/ci-artifacts/
    ref: main
    dockerfile_path: build/Dockerfile
  user:
    service_account: ci-artifacts
    role: cluster-admin
secrets:
  psap-ods-secret:
    env_key: PSAP_ODS_SECRET_PATH

workloads:
  notebook-burst:
    command_group: notebooks
    test_args:
    - icelake
    - notebook_test_burst
    steps:
      test:
        command: notebooks test run_tests_and_plots

  notebook-gating:
    command_group: notebooks
    test_args:
    - icelake
    - notebook_gating_test
    steps:
      test:
        command: notebooks test run_tests_and_plots

  notebook-scale-test:
    command_group: notebooks
    test_args:
    - icelake_notebook_test
    steps:
      prepare:
        command: notebooks test cleanup_rhods
      test:
        command: notebooks test run_tests_and_plots
      gather:
        command: utils gather-extra
        always_run: true

  notebook-just-scale-test:
    command_group: notebooks
    test_args:
    - icelake_notebook_test
    steps:
      test:
        command: notebooks test run_tests_and_plots

  notebook-scale-test-light:
    command_group: notebooks
    test_args:
    - notebooks_light
    - notebook_test
    steps:
      prepare:
        command: notebooks test cleanup_rhods
      test:
        command: notebooks test run_tests_and_plots

  notebook-scale-test-scaleup:
    command_group: notebooks
    test_args:
    - icelake_notebook_test_scaleup
    steps:
      cleanup:
        command: notebooks test cleanup_rhods
      test:
        command: notebooks test run_tests_and_plots
      gather:
        command: utils gather-extra
        alway_run: true

  notebook-scale-test-burst:
    command_group: notebooks
    test_args:
    - icelake_notebook_test_burst
    steps:
      cleanup:
        command: notebooks test cleanup_rhods
      test:
        command: notebooks test run_tests_and_plots
      gather:
        command: utils gather-extra
        alway_run: true

  pipelines:
    command_group: pipelines
    test_args:
    - icelake
    steps:
      pre_cleanup_cluster:
        command: pipelines test cleanup_cluster_ci
      prepare:
        command: pipelines test prepare_ci
      test:
        command: pipelines test test_ci
      post_cleanup_cluster:
        command: pipelines test cleanup_cluster_ci
        alway_run: true
