base_image:
  namespace: ci-artifacts
  imagestream: ci-artifacts
  repo:
    url: https://github.com/openshift-psap/ci-artifacts/
    ref: main
    dockerfile_path: build/Dockerfile
  user:
    service_account: ci-artifacts
    role: cluster-admin
secrets:
  psap-ods-secret:
    env_key: PSAP_ODS_SECRET_PATH

workloads:
  notebook-scale-test:
    command_group: notebooks
    test_args:
    - icelake_notebook_test
    steps:
      prepare:
        command: notebooks test cleanup_rhods
      test:
        command: notebooks test run_tests_and_plots
      gather:
        command: utils gather-extra
        always_run: true

  pipelines:
    command_group: rhods
    test_args:
    - icelake
    steps:
      pre_cleanup_cluster:
        command: pipelines test cleanup_cluster_ci
      prepare:
        command: pipelines test prepare_ci
      test:
        command: pipelines test test_ci
      post_cleanup_cluster:
        command: pipelines test cleanup_cluster_ci
        alway_run: true

  codeflare-light:
    command_group: rhods
    test_args:
    steps:
      test:
        command: codeflare test test_ci

  load-aware-light:
    command_group: rhods
    test_args:
    steps:
      test:
        command: load-aware test test_ci
