---
- name: Create the artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts"
    state: directory
    mode: '0755'

- name: Run the benchmark
  shell: |
    {{ mac_ai_remote_llama_cpp_run_bench_prefix }} {{ mac_ai_remote_llama_cpp_run_bench_path }} \
        --model {{ mac_ai_remote_llama_cpp_run_bench_name }} \
        --n-gpu-layers {{ mac_ai_remote_llama_cpp_run_bench_ngl }} \
    {% if mac_ai_remote_llama_cpp_run_bench_verbose -%}
        --verbose 2> "{{ artifact_extra_logs_dir }}/artifacts/verbose.log" \
    {% endif -%}
        > "{{ artifact_extra_logs_dir }}/artifacts/llama-bench.log"
