skip_list:
  # Hide "wrong indentation: expected 4 but found 2 (indentation)"
  # until we find out how to properly configure it
  - 'yaml'
  # Do not force galaxy info in meta/main.yml
  - 'meta-no-info'
  # Hide "Commands should not change things if nothing needs doing"
  - 'no-changed-when'
  # Hide "Role name 'xxx_yyy' does not match ``^[a-z][a-z0-9_]+$`` pattern"
  - 'role-name'
  ## The following Ansible lint rules are the ones that are currently
  ## part of the main lint checks that are not adresses in this repo
  ## The following skip rules represent 3143 failure(s), 12 warning(s) on 852 files.
  - 'command-instead-of-module'
  - 'command-instead-of-shell'
  - 'deprecated-local-action'
  - 'key-order[task]'
  - 'jinja[spacing]'
  - 'no-free-form'
  - 'chema[meta]'
  - 'name[missing]'
  - 'var-naming[no-reserved]'
  - 'var-naming[no-role-prefix]'
  - 'var-naming[pattern]'
  - 'yaml[colons]'
  - 'yaml[commas]'
  - 'yaml[comments]'
  - 'yaml[empty-lines]'
  - 'yaml[indentation]'
  - 'yaml[key-duplicates]'
  - 'yaml[line-length]'
  - 'yaml[new-line-at-end-of-file]'
  - 'yaml[octal-values]'
  - 'yaml[trailing-spaces]'
  - 'yaml[truthy]'
  - 'name[template]'
  - 'name[casing]'
  - 'risky-file-permissions'
  - 'risky-shell-pipe'
  - 'ignore-errors'
  - 'no-changed-when'
  - 'fqcn'
  - 'args[module]'
