---
- name: Ensure that the parent directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ remote_download_dest | dirname }}"
    mode: '0755'


- name: Download the source file
  ansible.builtin.get_url:
    url: "{{ remote_download_source }}"
    dest: "{{ remote_download_dest }}"
    mode: "0755"
    force: "{{ remote_download_force }}"

- name: Show the sha of the file
  command:
    sha256sum "{{ remote_download_dest }}"

- name: Make the file executable
  command:
    chmod u+x "{{ remote_download_dest }}"
  when: remote_download_executable | bool

- name: Extract the tarball
  command:
    tar xf "{{ remote_download_dest }}" -C "{{ remote_download_dest | dirname }}"
  when: remote_download_tarball | bool
