---
- name: Ensure that GRPCurl is available
  shell:
    which grpcurl

- name: Create the artifact directory
  file:
    path: "{{ artifact_extra_logs_dir }}/{{ watsonx_serving_validate_model_inference_service_name }}"
    state: directory
    mode: '0755'

- name: Get the name of the KSVC
  shell:
    set -o pipefail;
    oc get ksvc
       -lserving.kserve.io/inferenceservice={{ watsonx_serving_validate_model_inference_service_name }}
       -n {{ watsonx_serving_validate_model_namespace }}
       -ojsonpath='{.items[0].status.url}'
       | sed 's|https://||'
  register: ksvc_hostname_cmd


- name: Wait for the model to answer successfully
  shell: |
    set -o pipefail
    GRPCURL_DATA=$(echo "{{ watsonx_serving_validate_model_query_data }}" | sed "s/'/\"/g")
    grpcurl \
      -insecure \
      -d "$GRPCURL_DATA" \
      -H "mm-model-id: {{ watsonx_serving_validate_model_model_id }}" \
      {{ ksvc_hostname_cmd.stdout }}:443 \
      caikit.runtime.Nlp.NlpService/TextGenerationTaskPredict \
      > {{ artifact_extra_logs_dir }}/{{ watsonx_serving_validate_model_inference_service_name }}/TextGenerationTaskPredict.answer
  register: grpc1_working_cmd
  until: grpc1_working_cmd.rc == 0
  retries: 600
  delay: 1

- name: Save the number of attempts of the first call
  local_action:
    copy content={{ grpc1_working_cmd }} dest={{ artifact_extra_logs_dir }}/{{ watsonx_serving_validate_model_inference_service_name }}/attempts_1.json mode='0644'

- name: Query the model 2nd endpoint
  shell: |
    set -o pipefail
    GRPCURL_DATA=$(echo "{{ watsonx_serving_validate_model_query_data }}" | sed "s/'/\"/g")
    grpcurl \
      -insecure \
      -d "$GRPCURL_DATA" \
      -H "mm-model-id: {{ watsonx_serving_validate_model_model_id }}" \
      {{ ksvc_hostname_cmd.stdout }}:443 \
      caikit.runtime.Nlp.NlpService/ServerStreamingTextGenerationTaskPredict \
      > {{ artifact_extra_logs_dir }}/{{ watsonx_serving_validate_model_inference_service_name }}/ServerStreamingTextGenerationTaskPredict.answer
  register: grpc2_working_cmd
  until: grpc2_working_cmd.rc == 0
  retries: 600
  delay: 1

- name: Save the number of attempts of the second call
  local_action:
    copy content={{ grpc2_working_cmd }} dest={{ artifact_extra_logs_dir }}/{{ watsonx_serving_validate_model_inference_service_name }}/attempts_2.json mode='0644'
