apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.access.redhat.com/ubi8/nginx-120:latest
        command: ["nginx", "-g", "daemon off; error_log /dev/stdout info;"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-dir
          mountPath: /opt/app-root/src
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: data-dir
        configMap:
          defaultMode: 0777
          name: nginx-content
      - name: nginx-config
        configMap:
          defaultMode: 0777
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: nginx
