---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3cmd-config
data:
  s3cfg: |
    # Setup endpoint
    host_base = $S3_HOST_BASE
    host_bucket = $S3_HOST_BUCKET
    bucket_location = us-east-1
    use_https = False

    # Setup access keys
    access_key = $S3_ACCESS_KEY
    secret_key = $S3_SECRET_KEY
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    deployment: ods-ci
  name: ods-ci
spec:
  parallelism: {{ rhods_test_jupyterlab_user_count }}
  completions: {{ rhods_test_jupyterlab_user_count }}
  activeDeadlineSeconds: 18000
  backoffLimit: 0
  completionMode: Indexed
  template:
    metadata:
      name: ods-ci-loadtest
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - image: "{{ rhods_test_image }}"
        imagePullPolicy: Always
        name: ods-ci
        command: ['bash', '/mnt/rhods-jupyterlab-entrypoint/entrypoint.sh']
        env:
        - name: RUN_ROBOT_TEST_CASE
          value: "{{ rhods_test_jupyterlab_ods_ci_test_case }}"
        - name: ARTIFACTS_DIR
          value: /mnt/shared-dir/ods-ci
        - name: RUN_ROBOT_EXCLUDE_TAGS
          value: "{{ rhods_test_jupyterlab_artifacts_exclude_tags }}"
        volumeMounts:
        - name: shared-dir
          mountPath: /mnt/shared-dir
        - name: ods-ci-test-variables
          mountPath: /mnt/ods-ci-test-variables
        - name: rhods-jupyterlab-entrypoint
          mountPath: /mnt/rhods-jupyterlab-entrypoint
        resources:
          requests:
            memory: 750M
            cpu: 0.2
          limits:
            memory: 750M
            cpu: 0.2
      - image: "quay.io/centos/centos:stream8"
        name: artifacts-exporter
        command: ['bash', '/mnt/rhods-jupyterlab-entrypoint/artifacts-exporter.sh']
        env:
        - name: ARTIFACTS_COLLECTED
          value: "{{ rhods_test_jupyterlab_artifacts_collected }}"
        - name: ARTIFACTS_DIR
          value: /mnt/shared-dir/ods-ci
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: s3cmd-config
          mountPath: /mnt/s3-config
        - name: shared-dir
          mountPath: /mnt/shared-dir
        - name: ods-ci-test-variables
          mountPath: /mnt/ods-ci-test-variables
        - name: rhods-jupyterlab-entrypoint
          mountPath: /mnt/rhods-jupyterlab-entrypoint
      restartPolicy: Never
      volumes:
      - name: ods-ci-test-variables
        secret:
          secretName: ods-ci-test-variables
      - name: s3cmd-config
        configMap:
          name: s3cmd-config
      - name: rhods-jupyterlab-entrypoint
        configMap:
          name: rhods-jupyterlab-entrypoint
      - name: shared-dir
        emptyDir: {}
