---
- name: Fail if the tag key is empty
  fail: msg="Tag key is empty"
  when: not cluster_destroy_ocp_tag

- name: Fail if the tag value is empty
  fail: msg="Tag value is empty"
  when: not cluster_destroy_ocp_value

- name: Fail if the region is empty
  fail: msg="region is empty"
  when: not cluster_destroy_ocp_region

- name: Create openshift-installer metadata.json
  template:
    src: "{{ cluster_destroy_ocp_metadata_json }}"
    dest: "{{ artifact_extra_logs_dir }}/metadata.json"
    mode: 0400

- name: Get the path of the openshift-installer
  when: not openshift_installer
  shell:
    set -o pipefail;
    ls subprojects/deploy-cluster/utils/installers/*/openshift-install | head -1
  register: openshift_installer_cmd

- name: Trigger openshift-installer cluster deletion
  command: |
    {{ cluster_destroy_ocp_openshift_installer | default(openshift_installer_cmd) }}
      destroy cluster
        --dir "{{ artifact_extra_logs_dir }}"
        --log-level=debug
