---
- name: Create the artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts"
    state: directory
    mode: '0755'

- name: Set the name of the exit file
  set_fact:
    exit_file: /tmp/exit_topsail_top_capture

- name: Ensure that top is not currently running
  command:
    touch {{ exit_file }}
  failed_when: false

- name: Stop here if only stopping
  meta: end_play
  when: mac_ai_remote_capture_cpu_ram_usage_stop | bool


- name: Give a bit of time for the previous top command to terminate
  command:
    sleep 5

- name: Start capturing the CPU and RAM usage
  shell: |
    rm -f {{ exit_file }}
    nohup bash > "{{ artifact_extra_logs_dir }}/artifacts/cpu_ram_usage.txt"  -c '
      set -o pipefail;
      while true; do
        top -l 1 | grep -E "^CPU|^Phys"
        sleep 1;
        if [[ -e "{{ exit_file }}" ]]; then
          echo Exiting.
          exit 0
        fi
      done' &
