apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-psap/topsail?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push"
      && target_branch == "main"
      && (!".tekton/**".pathChanged() || ".tekton/fms-hf-tuning-push.yaml".pathChanged())
  name: topsail-plot
  labels:
    build.appstudio.redhat.com/pipeline: "topsail-plot"
spec:
  params: &params
  - name: git-url
    value: '{{source_url}}'
  - name: PROJECT
    type: string
    description: |
      The name of the project to launch
  - name: URL
    type: string
    description: |
      The URL to replot
  - name: PRESETS
    type: string
    description: |
      The names of the presets to apply
    default: ""

  pipelineSpec:
  results:
  tasks:
  - name: generate_plots_from_pr_args
    taskSpec:
      description: Task to create / manage data used across the pipeline
      results:
      - name: prepare
        steps:
        - name: generate_plots_from_pr_args
          image: registry.access.redhat.com/ubi9/ubi-minimal
          script: |
            #!/bin/sh
            run $PROJECT test generate_plots_from_pr_args
