- name: Generate load timeline
  shell:
    python3 {{ load_timeline_generator }} {{ load_aware_scale_test_distribution }} {{ load_aware_scale_test_duration}} {{ load_aware_scale_test_instances }} "{{ artifact_extra_logs_dir }}/schedule_plan.yaml"

- name: Run test workload with scheduler and load timeline
  shell:
    python3 {{ pod_start_scheduler }} {{ load_aware_scale_test_scheduler }} {{ load_aware_scale_test_namespace }} "{{ artifact_extra_logs_dir }}/schedule_plan.yaml" "{{ artifact_extra_logs_dir }}/schedule_execution.yaml"

- name: Wait for workloads to finish
  shell:
    oc get pods -n {{ load_aware_scale_test_namespace }} | awk 'NR > 1 { print $3 }'
  register: load_aware_workload
  delay: 60
  retries: 120
  until:
    "'Running' not in load_aware_workload.stdout
      and 'Pending' not in load_aware_workload.stdout
      and 'Failed' not in load_aware_workload.stdout
      and 'ContainerCreating' not in load_aware_workload.stdout"

- name: Dump info about scheduler resources
  shell: |
    oc get pods -n {{ load_aware_scale_test_namespace }} > "{{ artifact_extra_logs_dir }}/all_pods.status" 
    oc get pods -n {{ load_aware_scale_test_namespace }} -ojson > "{{ artifact_extra_logs_dir }}/all_pods.json"
