- name: Create coreutils ns
  command:
    oc apply -f {{ coreutils_ns }}

- name: Create coreutils-deps image stream
  command:
    oc apply -f {{ deps_imagestream }}

- name: Create coreutils-make image stream
  command:
    oc apply -f {{ make_imagestream }}

- name: Create make buildconfig
  command:
    oc apply -f {{ make_buildconfig }}

- name: Create deps buildconfig
  command:
    oc apply -f {{ deps_buildconfig }}

- name: Wait for coreutils-deps to finish building
  shell:
    oc get istag/coreutils-deps:latest -n coreutils
      | awk 'NR > 1 {print $1}'
  register: deps_image
  delay: 15
  retries: 80
  until: deps_image.stdout == "coreutils-deps:latest"

- name: Wait for coreutils-make to finish building
  shell:
    oc get istag/coreutils-make:latest -n coreutils
      | awk 'NR > 1 {print $1}'
  register: make_image
  delay: 15
  retries: 80
  until: make_image.stdout == "coreutils-make:latest"

- name: Generate load timeline
  shell:
    python3 {{ load_timeline_generator }} {{ load_aware_scale_test_distribution }} {{ load_aware_scale_test_duration}} {{ load_aware_scale_test_instances }} > "{{ artifact_extra_logs_dir }}/load_aware_load_timeline.log"

- name: Run test workload with default scheduler and load timeline
  shell:
    cat "{{ artifact_extra_logs_dir }}/load_aware_load_timeline.log"
      | python3 {{ pod_start_scheduler }} default > "{{ artifact_extra_logs_dir }}/default_workload_scheduler.log"

- name: Wait for default workloads to finish
  shell:
    oc get pods -n coreutils | awk 'NR > 1 { print $3 }'
  register: load_aware_workload
  delay: 60
  retries: 120
  until:
    "'Running' not in load_aware_workload.stdout
      and 'Pending' not in load_aware_workload.stdout
      and 'Failed' not in load_aware_workload.stdout
      and 'ContainerCreating' not in load_aware_workload.stdout"

- name: Dump info about default scheduler resources
  shell: |
    oc get pods -n coreutils > "{{ artifact_extra_logs_dir }}/all_default_pods.status" 
    oc get pods -n coreutils -ojson > "{{ artifact_extra_logs_dir }}/all_default_pods.json"

- name: Cleanup pods from default test
  command:
    oc delete pods --all -n coreutils

- name: Run test pod with trimaran scheduler and load timeline
  shell:
    cat "{{ artifact_extra_logs_dir }}/load_aware_load_timeline.log"
      | python3 {{ pod_start_scheduler }} trimaran > "{{ artifact_extra_logs_dir }}/trimaran_workload_scheduler.log"

- name: Wait for default workloads to finish
  shell:
    oc get pods -n coreutils | awk 'NR > 1 { print $3 }'
  register: load_aware_workload
  delay: 60
  retries: 120
  until:
    "'Running' not in load_aware_workload.stdout
      and 'Pending' not in load_aware_workload.stdout
      and 'Failed' not in load_aware_workload.stdout
      and 'ContainerCreating' not in load_aware_workload.stdout"


- name: Dump info about trimaran resources
  shell: |
    oc get pods -n coreutils > "{{ artifact_extra_logs_dir }}/all_trimaran_pods.status" 
    oc get pods -n coreutils -ojson > "{{ artifact_extra_logs_dir }}/all_trimaran_pods.json"

- name: Cleanup namespace for coreutils
  command:
    oc delete -f {{ coreutils_ns }}
