---
- name: Log whoami
  shell:
    whoami

- name: "Get the stats of the lock directory: {{ jump_ci_ensure_lock_cluster }}"
  stat:
    path: "/tmp/{{ jump_ci_ensure_lock_cluster }}"
  register: lock_directory_stat

- name: Fail if the lock directory doesn't exist
  fail: msg="The lock directory '/tmp/{{ jump_ci_ensure_lock_cluster }}' does not exists"
  when: not lock_directory_stat.stat.exists
