name: "Prepare TOPSAIL minimal ubuntu image"

runs:
  using: "composite" # <-- this is the important part
  steps:
  - name: Install dependencies
    shell: bash
    run: |
      python3 -m pip install fire pyyaml jsonpath_ng joblib
