---
- name: Delete the LDAP resources
  command: oc delete -f "{{ cluster_deploy_ldap_resources }}" --ignore-not-found

- name: Create the LDAP bind secret resource
  command: oc delete -f "{{ cluster_deploy_ldap_bind_secret_template }}" --ignore-not-found

- name: Create the LDAP secret resource
  command: oc delete -f "{{ cluster_deploy_ldap_secret_template }}" --ignore-not-found

- name: Set a dummy IDP name
  set_fact:
    cluster_deploy_ldap_idp_name: dummy

- name: Apply the Oauth template
  template:
    src: "{{ cluster_deploy_ldap_oauth }}"
    dest: "{{ artifact_extra_logs_dir }}/001_oauth_ldap.yml"
    mode: 0400

- name: Delete the LDAP Oauth resource
  when:
  - not cluster_undeploy_ldap_use_rosa
  - not cluster_undeploy_ldap_use_ocm
  shell:
    set -o pipefail;
    oc get -f "{{ artifact_extra_logs_dir }}/001_oauth_ldap.yml" -ojson | jq 'del(.spec.identityProviders)' | oc apply -f-

- name: Delete the ldap namespace
  command:
    oc delete namespace openldap --ignore-not-found

- name: Undeploy on ROSA
  when: cluster_undeploy_ldap_use_rosa | length > 0
  block:
  - name: Delete the IDP resource
    command:
      rosa delete idp "{{ cluster_undeploy_ldap_idp_name }}"
          --cluster "{{ cluster_undeploy_ldap_use_rosa }}"

- name: Undeploy on OCM
  when: cluster_undeploy_ldap_use_ocm | length > 0
  block:
  - name: Delete the IDP resource
    command:
      ocm delete idp "{{ cluster_undeploy_ldap_idp_name }}"
          --cluster "{{ cluster_undeploy_ldap_use_ocm }}"
