secrets:
  dir:
    name: psap-ods-secret
    env_key: PSAP_ODS_SECRET_PATH
  private_key_filename: jumpci_privatekey
  bastion_host_filename: jumpci_bastion_host
  jump_host_filename: jumpci_jump_host
ssh_tunnel:
  # creates a tunnel to the bastion via the jump host, if enabled
  enabled: false
  local_host_port: 2500
  verbose: false # will leak host names if enabled
cluster:
  name: null
ssh:
  flags:
  - -oStrictHostKeyChecking=no
  - -oUserKnownHostsFile=/dev/null
skip_list: {}
