secrets:
  dir:
    name: psap-ods-secret
    env_key: PSAP_ODS_SECRET_PATH
  private_key_filename: jumpci_privatekey
  bastion_host_filename: jumpci_bastion_host
  jump_host_filename: jumpci_jump_host
ssh_tunnel:
  # creates a tunnel to the bastion via the jump host, if enabled
  enabled: false
  local_host_port: 2500
  verbose: false # will leak host names if enabled
cluster:
  name: icelake
ssh:
  flags:
  - -oStrictHostKeyChecking=no
  - -oUserKnownHostsFile=/dev/null
  - -o LogLevel=ERROR
skip_list: {}
env:
  skip_list:
    by_name: [PATH, KUBECONFIG, HOME, PWD, DISPLAY, LANG, USER, LOGNAME, SHELL, _, OLDPWD, DBUS_SESSION_BUS_ADDRESS, LC_CTYPE, LSCOLOR, ARTIFACT_DIR, PYTHONPATH, PSAP_ODS_SECRET_PATH]
    by_prefix: [BASH_, XDG_, TOPSAIL_]
exec_list:
  _only_: false
  # keep these steps enabled for the jump-ci to work
  lock_cluster: true
  prepare_jump_ci: true
  unlock_cluster: true

  pre_cleanup_ci: null
  prepare_ci: null
  test_ci: null
  post_cleanup_ci: null
