---
cluster_deploy_nginx_server_deployment: roles/cluster/cluster_deploy_nginx_server/templates/deploy_nginx.yaml.j2
cluster_deploy_nginx_server_config_file: roles/cluster/cluster_deploy_nginx_server/templates/nginx.conf.j2
