---
# Define common command templates (shared across all platforms)
- name: Set common commands
  set_fact:
    initial_prune_command: "{{ container_bench_image_build_large_build_context_benchmark_runtime }} system prune -a -f"
    cleanup_commands: |
      {{ container_bench_image_build_large_build_context_benchmark_runtime }} rmi -f large-build-context-benchmark
      {{ container_bench_image_build_large_build_context_benchmark_runtime }} system prune -a -f
    dockerfile_content: |
      FROM scratch
      COPY random-1 random-1
      COPY random-10 random-10
    build_context_path: "{{ '$env:USERPROFILE\\large-build-context' if ansible_os_family == 'Windows' else '${HOME}/large-build-context' }}"

- name: Set platform-specific paths
  set_fact:
    benchmark_command: "{{ container_bench_image_build_large_build_context_benchmark_runtime }} build -t large-build-context-benchmark {{ build_context_path }}"

- name: Include Unix/Linux tasks
  include_tasks: unix.yml
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
