# Check repository consistency
name: Check consistency

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install fire pyyaml

      - name: Check that all the variables point to existing files
        run: ./run_toolbox.py repo validate_role_files

      - name: Check that all the variables defined are actually used
        run: ./run_toolbox.py repo validate_role_vars_used
