---
- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/{{ jump_ci_prepare_topsail_repo_owner }}/{{ jump_ci_prepare_topsail_repo_name }}.git'
    dest: "/tmp/{{ jump_ci_prepare_topsail_cluster_lock }}/topsail"
    version: "{% if jump_ci_prepare_topsail_pr_number %}refs/pull/{{ jump_ci_prepare_topsail_pr_number }}/merge{% else %}main{% endif %}"

- name: Build image {{ jump_ci_prepare_topsail_image_name }}
  shell:
    echo podman build ...
